backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)
# This line should *not* be indented
media_folder: '/src/content/images/uploads' # Media files will be stored in the repo under images/uploads
